import React from 'react';
import { motion } from 'framer-motion';
import { ShieldAlert, Zap, ClipboardList, Hammer, CreditCard, AlertTriangle, ChevronRight, FileText } from 'lucide-react';
import { Link } from 'react-router-dom';

const sections = [
    {
        id: '01',
        title: 'Acceptance of Terms',
        icon: <ClipboardList size={22} />,
        color: '#6366f1',
        content: [
            'By accessing or using the DMS Metals platform — including uploading CAD files, requesting quotes, or placing manufacturing orders — you agree to be bound by these Terms of Service.',
            'If you are using the platform on behalf of a company or organization, you represent that you have the authority to bind that entity to these terms.',
            'We reserve the right to update these terms at any time. Continued use of the platform after changes constitutes acceptance of the revised terms.'
        ]
    },
    {
        id: '02',
        title: 'CAD File Accuracy',
        icon: <Zap size={22} />,
        color: '#e31b23',
        content: [
            'Users are solely responsible for the accuracy and correctness of all uploaded 3D models and DXF drawings. DMS Metals applies automated geometry analysis but does not validate functional design intent.',
            'Quotes generated by our instant pricing engine are based entirely on the specifications extracted from your uploaded files. Discrepancies between the file and your intended part are the customer\'s responsibility.',
            'We strongly recommend verifying all automated measurements and tolerances before proceeding to production.'
        ]
    },
    {
        id: '03',
        title: 'Manufacturing & Quality',
        icon: <Hammer size={22} />,
        color: '#10b981',
        content: [
            'All manufacturing is performed to the tolerances specified in your order. Standard tolerances are ±0.1mm unless explicitly agreed otherwise in writing.',
            'Changes requested after order placement may incur additional fees and lead time adjustments. Major design revisions may require a new quote.',
            'DMS Metals guarantees the quality of our manufacturing processes. If a part does not conform to the stated tolerances, we will re-manufacture or provide a refund at our discretion.'
        ]
    },
    {
        id: '04',
        title: 'Intellectual Property',
        icon: <ShieldAlert size={22} />,
        color: '#f59e0b',
        content: [
            'You retain full ownership of all CAD files and designs you upload. By submitting files to DMS Metals, you grant us a limited, non-exclusive license solely for the purpose of generating quotes and manufacturing the ordered parts.',
            'This license terminates upon order completion or cancellation. DMS Metals will not use your designs to produce parts for any third party without your explicit written consent.',
            'DMS Metals\' own pricing algorithms, 3D analysis tools, and platform software remain the exclusive intellectual property of DMS Metals.'
        ]
    },
    {
        id: '05',
        title: 'Payment & Billing',
        icon: <CreditCard size={22} />,
        color: '#8b5cf6',
        content: [
            'All prices quoted are in USD and are valid for 48 hours from the time of quote generation unless otherwise stated. Material price fluctuations may affect quotes after this period.',
            'Full payment is required before production begins for new customers. Established accounts may qualify for net-30 payment terms upon approval.',
            'Cancellations made before production has started are fully refunded. Cancellations after production begins may be subject to material and labor costs already incurred.'
        ]
    },
    {
        id: '06',
        title: 'Limitation of Liability',
        icon: <AlertTriangle size={22} />,
        color: '#ef4444',
        content: [
            'DMS Metals\' liability is limited to the total value of the specific order in question. We are not liable for indirect, consequential, or incidental damages arising from delays or manufacturing defects.',
            'We are not responsible for design failures, patent infringements, or safety issues arising from customer-provided specifications. Always have critical parts independently verified by a qualified engineer.',
            'Force majeure events including supply chain disruptions, natural disasters, or regulatory changes may affect delivery timelines without incurring liability on our part.'
        ]
    }
];

const TermsOfService = () => {
    return (
        <div style={{ background: '#fff', minHeight: '100vh' }}>
            {/* Hero */}
            <section style={{ background: 'linear-gradient(135deg, #0f172a 0%, #1a0a0a 60%, #0f172a 100%)', padding: '100px 24px 80px', position: 'relative', overflow: 'hidden' }}>
                <div style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundImage: 'radial-gradient(circle at 80% 50%, rgba(227,27,35,0.08) 0%, transparent 60%), radial-gradient(circle at 20% 20%, rgba(99,102,241,0.06) 0%, transparent 50%)', pointerEvents: 'none' }} />
                <div style={{ maxWidth: 800, margin: '0 auto', position: 'relative', zIndex: 1 }}>
                    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
                        <nav style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: '0.8rem', fontWeight: 600, color: 'rgba(255,255,255,0.45)', marginBottom: 32, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                            <Link to="/" style={{ color: 'inherit', textDecoration: 'none' }}>Home</Link>
                            <ChevronRight size={12} />
                            <span style={{ color: '#fff' }}>Terms of Service</span>
                        </nav>
                        <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: 'rgba(227,27,35,0.12)', border: '1px solid rgba(227,27,35,0.3)', borderRadius: 50, padding: '6px 16px', marginBottom: 20 }}>
                            <FileText size={13} style={{ color: '#f87171' }} />
                            <span style={{ fontSize: '0.72rem', fontWeight: 800, color: '#f87171', letterSpacing: '1.5px', textTransform: 'uppercase' }}>Legal Document</span>
                        </div>
                        <h1 style={{ fontSize: 'clamp(2.4rem, 5vw, 3.5rem)', fontWeight: 900, color: '#fff', margin: '0 0 20px', lineHeight: 1.1, letterSpacing: '-0.02em' }}>Terms of Service</h1>
                        <p style={{ fontSize: '1.15rem', color: 'rgba(255,255,255,0.65)', lineHeight: 1.7, maxWidth: 580, margin: 0 }}>
                            Last updated April 1, 2026. Please read these terms carefully before starting your manufacturing project.
                        </p>
                    </motion.div>
                </div>
            </section>

            {/* Table of Contents */}
            <div style={{ borderBottom: '1px solid #f1f5f9', padding: '0 24px' }}>
                <div style={{ maxWidth: 800, margin: '0 auto', display: 'flex', flexWrap: 'wrap', gap: '0', overflow: 'hidden' }}>
                    {sections.map((s) => (
                        <a key={s.id} href={`#section-${s.id}`} style={{ padding: '16px 20px', fontSize: '0.8rem', fontWeight: 700, color: '#64748b', textDecoration: 'none', borderBottom: '2px solid transparent', transition: 'all 0.2s', whiteSpace: 'nowrap' }}
                            onMouseEnter={e => { e.target.style.color = '#0f172a'; e.target.style.borderBottomColor = '#e31b23'; }}
                            onMouseLeave={e => { e.target.style.color = '#64748b'; e.target.style.borderBottomColor = 'transparent'; }}>
                            {s.id}. {s.title}
                        </a>
                    ))}
                </div>
            </div>

            {/* Content */}
            <main style={{ maxWidth: 800, margin: '0 auto', padding: '72px 24px 96px' }}>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 48 }}>
                    {sections.map((section, idx) => (
                        <motion.div
                            key={section.id}
                            id={`section-${section.id}`}
                            initial={{ opacity: 0, y: 24 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ duration: 0.5, delay: idx * 0.06 }}
                            style={{ display: 'flex', gap: 28, alignItems: 'flex-start', paddingBottom: 48, borderBottom: idx < sections.length - 1 ? '1px solid #f1f5f9' : 'none' }}
                        >
                            <div style={{ flexShrink: 0 }}>
                                <div style={{ width: 52, height: 52, borderRadius: 16, background: `${section.color}14`, border: `1.5px solid ${section.color}30`, display: 'flex', alignItems: 'center', justifyContent: 'center', color: section.color }}>
                                    {section.icon}
                                </div>
                            </div>
                            <div style={{ flex: 1 }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
                                    <span style={{ fontSize: '0.7rem', fontWeight: 900, color: section.color, letterSpacing: '2px', textTransform: 'uppercase', fontFamily: 'monospace' }}>{section.id}</span>
                                    <h2 style={{ fontSize: '1.3rem', fontWeight: 800, color: '#0f172a', margin: 0 }}>{section.title}</h2>
                                </div>
                                <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
                                    {section.content.map((para, i) => (
                                        <div key={i} style={{ display: 'flex', gap: 12 }}>
                                            <div style={{ width: 6, height: 6, borderRadius: '50%', background: section.color, flexShrink: 0, marginTop: 9 }} />
                                            <p style={{ fontSize: '1rem', color: '#475569', lineHeight: 1.75, margin: 0 }}>{para}</p>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </motion.div>
                    ))}
                </div>

                {/* Agreement Box */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    style={{ marginTop: 56, padding: '36px 40px', borderRadius: 20, background: '#fafafa', border: '1.5px solid #e2e8f0' }}
                >
                    <h3 style={{ fontSize: '1.1rem', fontWeight: 800, color: '#0f172a', margin: '0 0 12px' }}>By Using This Platform, You Agree</h3>
                    <p style={{ fontSize: '0.95rem', color: '#64748b', lineHeight: 1.7, margin: '0 0 20px' }}>
                        Clicking <strong style={{ color: '#0f172a' }}>"Proceed to Checkout"</strong> on our pricing tools constitutes your electronic signature and full acceptance of these manufacturing terms.
                    </p>
                    <Link to="/privacy-policy" style={{ fontSize: '0.85rem', color: '#6366f1', fontWeight: 700, textDecoration: 'none' }}>
                        ← Read our Privacy Policy
                    </Link>
                </motion.div>
            </main>
        </div>
    );
};

export default TermsOfService;
